default:
  paths:
    dane_raw: "dane/surowe/dane_surowe.csv"
    metoda: "dane/metoda/metoda.xlsx"
    dane_ostateczne: "dane/dane_ostateczne/dane_ostateczne.csv"
    dane_spss: "dane/dane_ostateczne/dane_spss.sav"
    codebook: "dane/codebooks/codebook.xlsx"
    interpretacje: "dane/interpretacje/opis_analiz.yml"
    interpretacje_edited: "dane/interpretacje/opis_analiz_edited.yml"
    reliability: "raporty/inne/reliability.docx"
    cache: ".cache"
  patterns:
    items: ""
  variables:
    ignored: ""
    scales: ""
  labels:
  report:
    introduction:
      program: "IBM SPSS 29"
      threshold: 0.05
      significanc_testing: two-tailed tests
  analyses:
    h1:
      dv:
      iv:
  hypotheses:
    h1: ""
    h2: ""





development:
  dataset: dev_path


production:
  dataset: prod_path
